//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public int Id_Client { get; set; }
        public string hebrew_name { get; set; }
        public string english_name { get; set; }
        public Nullable<System.DateTime> born_date { get; set; }
        public Nullable<int> city_code { get; set; }
        public string bank { get; set; }
        public string branch { get; set; }
        public string account_number { get; set; }
        public string identity_card { get; set; }
    
        public virtual cities cities { get; set; }
    }
}
